### ISSUE TITLE
Requires Projects

### ISSUE THREAD

**Issue by theplatformguy** [platformnow/environment-package#1]
The package requires a Argo AppProject to exists: The example to be used with the default is:

```
apiVersion: v1
kind: Namespace
metadata:
  name: test-project
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-project
  namespace: landscape-system
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - "*"
  sourceRepos:
    - '*'
status: {}
```

We need to create a Project Package and this file will be created
